# Generated by Django 2.0.13 on 2020-01-18 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imie')),
                ('answers', models.TextField(verbose_name='Odpowiedzi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Utworzony')),
            ],
            options={
                'verbose_name': 'Odpowiedź',
                'verbose_name_plural': 'Odpowiedzi',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Opis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.IntegerField(choices=[(1, 'Otwarte'), (2, 'Zamknięte')], verbose_name='Rodzaj pytania')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Opis')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event', verbose_name='Wydarzenie')),
            ],
            options={
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Pytania',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event', verbose_name='Wydarzenie'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
