# Generated by Django 2.0.13 on 2020-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Opis Wydarzenia'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nazwa Wydarzenia'),
        ),
    ]
